export const TIPS = [
  'Canta cinco minutos al día: el canto estira tu rango de tono y tu voz hablada se vuelve más expresiva.',
  'Las preguntas de sí o no suben al final; las afirmaciones bajan. Si todo te suena igual, exagera la diferencia.',
  'Tararea «mmm» antes de hablar: si sientes cosquillas en los labios, tu voz está bien colocada.',
  'Sube el tono en la palabra clave de cada frase y baja al terminar. Así suena seguro y no monótono.',
  'Afinar no es talento, es oído entrenado: escucha la nota, imagínala y después cántala.',
  'Agrupa tus ideas de tres en tres. El oído recuerda mejor los tríos: «vine, vi, vencí».',
  'Antes de hablar, exhala largo. Una exhalación lenta calma el pulso en segundos.',
  'Cambia «este» por un silencio de un segundo. El silencio transmite seguridad.',
  'Sostén el volumen en la última palabra de cada frase: ahí suele estar lo importante.',
  'Mira a una persona durante una frase completa y después cambia de persona.',
  'Empieza con una pregunta o un dato. Los primeros diez segundos deciden la atención.',
  'Una idea por frase. Si necesitas «y», «y», «y», parte la frase en dos.',
  'Cierra con una petición concreta: qué, quién y cuándo.',
  'Si te pierdes, resume lo último que dijiste. Ganas tiempo y ordenas la idea.',
  'Practica en voz alta, no en la mente: la boca también necesita ensayar.',
  'Usa números concretos: «tres de cada diez» se recuerda más que «muchos».',
  'Baja el ritmo en lo importante y agiliza lo secundario.',
  'Sonríe al empezar: cambia el tono de tu voz aunque no te vean.',
  'Las manos visibles generan confianza. Evita esconderlas o cruzarlas.',
  'Si te preguntan algo difícil, reconoce la pregunta antes de responder.',
  'Una historia necesita un obstáculo. Sin conflicto, no hay atención.',
  'Evita disculparte por hablar: «perdón que les quite tiempo» resta fuerza.',
  'Afirma lo que sabes. «Creo que» sobra cuando tienes certeza.',
  'Termina tu frase final y haz silencio. No añadas «y bueno, eso es todo».',
  'Bebe agua a temperatura ambiente antes de hablar; el agua fría tensa la garganta.',
  'Apóyate en el abdomen, no en la garganta, para subir el volumen.',
  'Ensaya el inicio y el cierre palabra por palabra; el medio, con ideas clave.',
  'Una pausa antes de un dato importante lo convierte en protagonista.',
  'Pregúntate: ¿qué quiero que recuerden al salir? Construye todo alrededor de eso.',
  'Habla a la última fila: tu voz se ajusta sola cuando imaginas la distancia.',
  'Las palabras concretas pintan imágenes: «un expediente de 400 páginas» vale más que «mucho trabajo».',
  'Si hablas con prisa, la audiencia siente prisa. Si respiras, respira contigo.',
  'Un buen ejemplo vale más que tres adjetivos.',
  'Varía el tono: sube en la pregunta, baja en la conclusión.',
  'Antes de una reunión, di tu idea principal en una sola frase en voz alta.',
  'Llega dos minutos antes: saludar a la gente convierte extraños en aliados.',
  'Graba en tu mente tres palabras clave, no un texto: así no te bloqueas.',
  'Respeta el tiempo: terminar un minuto antes siempre se agradece.',
  'Nombra a tu audiencia: «ustedes que atienden usuarios cada día…» conecta más que «la gente».',
  'Cuando uses una sigla, dila completa la primera vez.',
  'Tu postura cambia tu voz: pies firmes y hombros sueltos antes de empezar.',
  'Si sientes nervios, llámalos energía. El cuerpo responde a cómo lo nombras.',
  'Después de preguntar «¿alguna duda?», cuenta en silencio hasta cinco.',
  'Resume al final en una frase. Lo último que oyen es lo primero que recuerdan.',
  'Celebra tu progreso: cada práctica de hoy es un minuto menos de nervios mañana.',
];
